version: '3'
services:
    passport-app:
        build: .
        depends_on:
            - mongodbB
            - redis
        ports:
            - '3003:3003'
        redis:
            image: redis
        mongodbB: 
            image: mongo
        container_name: mongodb
