version: '3'
services:
    passport-app:
        build: .
        depends_on:
            - mongodbB
        ports:
            - '3003:3003'
        mongodbB:
            image: mongo
            ports: ['27017:27017']
            container_name: mongodb
